spring:
  application:
    name: ProductManager
  datasource:
    url: jdbc:mariadb://localhost:3306/product-manager
    username: root
    password: # hier kannst du dein Passwort einfügen
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
